
server:
  port: 5200

spring:
  application:
    name: cart-ms
  profiles:
    active: ${ACTIVE_PROFILE:qa}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

resilience4j:
  circuitbreaker:
    instances:
      cb-product-ms:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowSize: 10
        waitDurationInOpenState: 2s
        slidingWindowType: COUNT_BASED

  retry:
    metrics:
      enabled: true
    instances:
      retry-product-fetch:
        max-attempts: 5
        wait-duration: 5000


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      cb-product-ms:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 1
        slidingWindowSize: 10
        waitDurationInOpenState: 2s
        slidingWindowType: COUNT_BASED

  retry:
    metrics:
      enabled: true
    instances:
      retry-product-fetch:
        max-attempts: 5
        wait-duration: 5000


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    httptrace:
      enabled: true