server:
  port: 5000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
      - id: product-ms
        uri:
          lb://product-ms
        predicates:
          - Path=/api/products/**

      - id: cart-ms
        uri:
          lb://cart-ms
        predicates:
          - Path=/api/cart/**

      - id: order-ms
        uri:
          lb://order-ms
        predicates:
          - Path=/api/order/**


#      - id: product-ms-swagger
#        uri:
#          lb://product-ms
#        predicates:
#          - Path=/swagger-ui/index.html





