server:
  port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
          server:
            git:
              uri: https://github.com/ramanujds/shopping-app-config-demo
              clone-on-start: true
            default-label: main


