spring:
  config:
    import: optional:configserver:http://localhost:8888


# h2 properties

# spring:
    h2:
        console:
            enabled: true
            path: /h2-console
            web-allow-others: true
        datasource:
            url: ${CART_DB_URL:jdbc:h2:mem:cartdb}
            username: sa
            password:
            driver-class-name: org.h2.Driver
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            database: H2
            show-sql: true
            hibernate:
            ddl-auto: update
            format_sql: true

# Enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: refresh, beans, env, health, info, metrics, httptrace, loggers, threaddump, mappings, conditions, configprops, scheduledtasks, shutdown